import os

RABBITMQ_ACCESSION_QUEUE = 'ingest.metadata.accession.queue'
RABBITMQ_ACCESSION_QUEUE = os.environ.get('RABBITMQ_ACCESSION_QUEUE', RABBITMQ_ACCESSION_QUEUE)

RABBITMQ_ACCESSION_EXCHANGE = 'ingest.accession.exchange'
RABBITMQ_ACCESSION_EXCHANGE = os.environ.get('RABBITMQ_ACCESSION_EXCHANGE', RABBITMQ_ACCESSION_EXCHANGE)

RABBITMQ_HOST = 'amqp://127.0.0.1'
RABBITMQ_PORT = '5672'
RABBITMQ_URL = RABBITMQ_HOST + ':' + RABBITMQ_PORT
RABBITMQ_URL = os.path.expandvars(os.environ.get('RABBIT_URL', RABBITMQ_URL))

INGEST_API_HOST = 'http://localhost'
INGEST_API_PORT = '8080'

INGEST_API_URL = INGEST_API_HOST + ':' + INGEST_API_PORT
INGEST_API_URL = os.path.expandvars(os.environ.get('INGEST_API', INGEST_API_URL))
